version = 4.2.0
archive_dir = /etc/letsencrypt/archive/www.sglone.kz
cert = /etc/letsencrypt/live/www.sglone.kz/cert.pem
privkey = /etc/letsencrypt/live/www.sglone.kz/privkey.pem
chain = /etc/letsencrypt/live/www.sglone.kz/chain.pem
fullchain = /etc/letsencrypt/live/www.sglone.kz/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = c10a368bd184f20098d7f637d2e2abca
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
