

networks: 
  dev:

services:
  nginx: 
    image: nginx:stable-alpine
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on: 
      - backend
      - frontend
    networks:
      - dev
    restart: unless-stopped

  backend: 
    build: 
      context: ../backend
    networks:
      - dev
  
  frontend: 
    build: 
      context: ../frontend
    networks:
      - dev
  
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --email bersenev4dev@gmail.com -d www.sglone.kz -d sglone.kz --expand --agree-tos --non-interactive --keep-until-expiring
    restart: unless-stopped